import asyncio
import os
from playwright.async_api import async_playwright

async def main():
 # Start a separate app against test data; this check does not save or delete jobs.
 async with async_playwright() as p:
  browser=await p.chromium.launch(executable_path='/usr/bin/chromium',args=['--no-sandbox','--disable-dev-shm-usage'])
  page=await browser.new_page(viewport={'width':1440,'height':1100})
  await page.goto(os.environ.get('MKP_TEST_URL','http://127.0.0.1:8504'),wait_until='networkidle')
  await page.get_by_role('button',name='Confirm room layout',exact=True).click()
  await page.get_by_role('button',name='Add library unit',exact=True).click()
  await page.wait_for_timeout(600)
  await page.get_by_role('button',name='Add library unit',exact=True).click()
  frame=next(f for f in page.frames if 'mkp_designer2d' in f.url)
  await frame.wait_for_function('args && args.units.length===2')
  unit=frame.locator('polygon.unit').nth(0)
  await unit.scroll_into_view_if_needed();box=await unit.bounding_box()
  scale=await frame.evaluate('svg.getScreenCTM().a')
  await page.mouse.move(box['x']+box['width']/2,box['y']+box['height']/2)
  await page.mouse.down();await page.mouse.move(box['x']+box['width']/2+1000*scale,box['y']+box['height']/2+1000*scale,steps=8);await page.mouse.up()
  await frame.wait_for_function('args.units[0].row["X (mm)"]>990 && args.units[0].row["Y (mm)"]>1000')
  print('Drag passed',await frame.evaluate('args.units[0].row'))
  await frame.get_by_role('button',name='Rotate 90°').click()
  await frame.wait_for_function('args.units[0].row["Rotation (deg)"]===90')
  print('Rotate passed')
  await frame.locator('polygon.unit').nth(1).click()
  await frame.wait_for_function('args.selected===1')
  page.once('dialog',lambda dialog:dialog.accept())
  await frame.get_by_role('button',name='Delete selected').click()
  await frame.wait_for_function('args.units.length===1')
  print('Delete passed')
  await page.get_by_role('button',name='Approve and lock layout',exact=True).click()
  await frame.wait_for_function('args.locked===true')
  assert await frame.get_by_role('button',name='Rotate 90°').is_disabled()
  assert await page.get_by_role('button',name='Add library unit',exact=True).is_disabled()
  before=await frame.evaluate('JSON.stringify(args.units)')
  await frame.locator('polygon.unit').click()
  await frame.wait_for_function('pending===false')
  assert before==await frame.evaluate('JSON.stringify(args.units)')
  print('Lock passed')
  await page.get_by_text('I intend to revise this approved layout',exact=True).click()
  await page.get_by_role('button',name='Unlock approved layout',exact=True).click()
  await frame.wait_for_function('args.locked===false')
  print('Explicit unlock passed')
  await page.set_viewport_size({'width':1024,'height':900})
  await frame.locator('#plan').scroll_into_view_if_needed()
  await page.screenshot(path='/tmp/mkp-designer2d-browser.png')
  assert not await page.locator('[data-testid="stException"]').count()
  await browser.close()
asyncio.run(main())
